name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - run: npm install

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: cd ../../
      - run: npm install
      - run: npm run build
